[project]
name = "realtime-banking-modern-datastack"
version = "0.1.0"
description = "Banking modern data stack"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
  "apache-airflow==3.1.7",
  "psycopg2-binary~=2.9.9",
  "pyyaml~=6.0.1",
  "python-dotenv~=1.0.1",
  "requests~=2.32.0",
  "boto3~=1.34.0",
  "botocore~=1.34.0",
  "pandas>=2.2.0,<2.3.0",
  "fastparquet>=2024.5.0",
  "dbt-core~=1.9.0",
  "dbt-snowflake~=1.9.0",
  "faker",
  "kafka-python-ng",
  "cffi",
  "kafka-python>=2.3.0",
]

[tool.setuptools]
packages = ["banking_modern_datastack"]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
